<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreateCountryCodesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('country_codes', function (Blueprint $table) {
            $table->id();
            $table->string('code',2)->unique();
			$table->string('country');
            $table->timestamps();
        });
        DB::table('country_codes')->insert(array('code'=>'AF','country'=>'Afghanistan'));
		DB::table('country_codes')->insert(array('code'=>'AL','country'=>'Albania'));
		DB::table('country_codes')->insert(array('code'=>'DZ','country'=>'Algeria'));
		DB::table('country_codes')->insert(array('code'=>'AS','country'=>'American Samoa'));
		DB::table('country_codes')->insert(array('code'=>'AD','country'=>'Andorra'));
		DB::table('country_codes')->insert(array('code'=>'AO','country'=>'Angola'));
		DB::table('country_codes')->insert(array('code'=>'AI','country'=>'Anguilla'));
		DB::table('country_codes')->insert(array('code'=>'AQ','country'=>'Antarctica'));
		DB::table('country_codes')->insert(array('code'=>'AG','country'=>'Antigua and Barbuda'));
		DB::table('country_codes')->insert(array('code'=>'AR','country'=>'Argentina'));
		DB::table('country_codes')->insert(array('code'=>'AM','country'=>'Armenia'));
		DB::table('country_codes')->insert(array('code'=>'AW','country'=>'Aruba'));
		DB::table('country_codes')->insert(array('code'=>'AU','country'=>'Australia'));
		DB::table('country_codes')->insert(array('code'=>'AT','country'=>'Austria'));
		DB::table('country_codes')->insert(array('code'=>'AZ','country'=>'Azerbaijan'));
		DB::table('country_codes')->insert(array('code'=>'BS','country'=>'Bahamas'));
		DB::table('country_codes')->insert(array('code'=>'BH','country'=>'Bahrain'));
		DB::table('country_codes')->insert(array('code'=>'BD','country'=>'Bangladesh'));
		DB::table('country_codes')->insert(array('code'=>'BB','country'=>'Barbados'));
		DB::table('country_codes')->insert(array('code'=>'BY','country'=>'Belarus'));
		DB::table('country_codes')->insert(array('code'=>'BE','country'=>'Belgium'));
		DB::table('country_codes')->insert(array('code'=>'BZ','country'=>'Belize'));
		DB::table('country_codes')->insert(array('code'=>'BJ','country'=>'Benin'));
		DB::table('country_codes')->insert(array('code'=>'BM','country'=>'Bermuda'));
		DB::table('country_codes')->insert(array('code'=>'BT','country'=>'Bhutan'));
		DB::table('country_codes')->insert(array('code'=>'BO','country'=>'Bolivia'));
		DB::table('country_codes')->insert(array('code'=>'BA','country'=>'Bosnia and Herzegovina'));
		DB::table('country_codes')->insert(array('code'=>'BW','country'=>'Botswana'));
		DB::table('country_codes')->insert(array('code'=>'BV','country'=>'Bouvet Island'));
		DB::table('country_codes')->insert(array('code'=>'BR','country'=>'Brazil'));
		DB::table('country_codes')->insert(array('code'=>'IO','country'=>'British Indian Ocean Territory'));
		DB::table('country_codes')->insert(array('code'=>'VG','country'=>'British Virgin Islands'));
		DB::table('country_codes')->insert(array('code'=>'BN','country'=>'Brunei Darussalam'));
		DB::table('country_codes')->insert(array('code'=>'BG','country'=>'Bulgaria'));
		DB::table('country_codes')->insert(array('code'=>'BF','country'=>'Burkina Faso'));
		DB::table('country_codes')->insert(array('code'=>'BI','country'=>'Burundi'));
		DB::table('country_codes')->insert(array('code'=>'KH','country'=>'Cambodia'));
		DB::table('country_codes')->insert(array('code'=>'CM','country'=>'Cameroon'));
		DB::table('country_codes')->insert(array('code'=>'CA','country'=>'Canada'));
		DB::table('country_codes')->insert(array('code'=>'CV','country'=>'Cape Verde'));
		DB::table('country_codes')->insert(array('code'=>'KY','country'=>'Cayman Islands'));
		DB::table('country_codes')->insert(array('code'=>'CF','country'=>'Central African Republic'));
		DB::table('country_codes')->insert(array('code'=>'TD','country'=>'Chad'));
		DB::table('country_codes')->insert(array('code'=>'CL','country'=>'Chile'));
		DB::table('country_codes')->insert(array('code'=>'CN','country'=>'China'));
		DB::table('country_codes')->insert(array('code'=>'CX','country'=>'Christmas Island'));
		DB::table('country_codes')->insert(array('code'=>'CC','country'=>'Cocos'));
		DB::table('country_codes')->insert(array('code'=>'CO','country'=>'Colombia'));
		DB::table('country_codes')->insert(array('code'=>'KM','country'=>'Comoros'));
		DB::table('country_codes')->insert(array('code'=>'CD','country'=>'Congo'));
		DB::table('country_codes')->insert(array('code'=>'CG','country'=>'Congo'));
		DB::table('country_codes')->insert(array('code'=>'CK','country'=>'Cook Islands'));
		DB::table('country_codes')->insert(array('code'=>'CR','country'=>'Costa Rica'));
		DB::table('country_codes')->insert(array('code'=>'CI','country'=>'Cote D\'Ivoire'));
		DB::table('country_codes')->insert(array('code'=>'CU','country'=>'Cuba'));
		DB::table('country_codes')->insert(array('code'=>'CY','country'=>'Cyprus'));
		DB::table('country_codes')->insert(array('code'=>'CZ','country'=>'Czech Republic'));
		DB::table('country_codes')->insert(array('code'=>'DK','country'=>'Denmark'));
		DB::table('country_codes')->insert(array('code'=>'DJ','country'=>'Djibouti'));
		DB::table('country_codes')->insert(array('code'=>'DM','country'=>'Dominica'));
		DB::table('country_codes')->insert(array('code'=>'DO','country'=>'Dominican Republic'));
		DB::table('country_codes')->insert(array('code'=>'EC','country'=>'Ecuador'));
		DB::table('country_codes')->insert(array('code'=>'EG','country'=>'Egypt'));
		DB::table('country_codes')->insert(array('code'=>'SV','country'=>'El Salvador'));
		DB::table('country_codes')->insert(array('code'=>'GQ','country'=>'Equatorial Guinea'));
		DB::table('country_codes')->insert(array('code'=>'ER','country'=>'Eritrea'));
		DB::table('country_codes')->insert(array('code'=>'EE','country'=>'Estonia'));
		DB::table('country_codes')->insert(array('code'=>'ET','country'=>'Ethiopia'));
		DB::table('country_codes')->insert(array('code'=>'FO','country'=>'Faeroe Islands'));
		DB::table('country_codes')->insert(array('code'=>'FK','country'=>'Falkland Islands'));
		DB::table('country_codes')->insert(array('code'=>'FJ','country'=>'Fiji'));
		DB::table('country_codes')->insert(array('code'=>'FI','country'=>'Finland'));
		DB::table('country_codes')->insert(array('code'=>'FR','country'=>'France'));
		DB::table('country_codes')->insert(array('code'=>'GF','country'=>'French Guiana'));
		DB::table('country_codes')->insert(array('code'=>'PF','country'=>'French Polynesia'));
		DB::table('country_codes')->insert(array('code'=>'TF','country'=>'French Southern Territories'));
		DB::table('country_codes')->insert(array('code'=>'GA','country'=>'Gabon'));
		DB::table('country_codes')->insert(array('code'=>'GM','country'=>'Gambia'));
		DB::table('country_codes')->insert(array('code'=>'GE','country'=>'Georgia'));
		DB::table('country_codes')->insert(array('code'=>'DE','country'=>'Germany'));
		DB::table('country_codes')->insert(array('code'=>'GH','country'=>'Ghana'));
		DB::table('country_codes')->insert(array('code'=>'GI','country'=>'Gibraltar'));
		DB::table('country_codes')->insert(array('code'=>'GR','country'=>'Greece'));
		DB::table('country_codes')->insert(array('code'=>'GL','country'=>'Greenland'));
		DB::table('country_codes')->insert(array('code'=>'GD','country'=>'Grenada'));
		DB::table('country_codes')->insert(array('code'=>'GP','country'=>'Guadaloupe'));
		DB::table('country_codes')->insert(array('code'=>'GU','country'=>'Guam'));
		DB::table('country_codes')->insert(array('code'=>'GT','country'=>'Guatemala'));
		DB::table('country_codes')->insert(array('code'=>'GN','country'=>'Guinea'));
		DB::table('country_codes')->insert(array('code'=>'GW','country'=>'Guinea-Bissau'));
		DB::table('country_codes')->insert(array('code'=>'GY','country'=>'Guyana'));
		DB::table('country_codes')->insert(array('code'=>'HT','country'=>'Haiti'));
		DB::table('country_codes')->insert(array('code'=>'HM','country'=>'Heard and McDonald Islands'));
		DB::table('country_codes')->insert(array('code'=>'VA','country'=>'Holy See'));
		DB::table('country_codes')->insert(array('code'=>'HN','country'=>'Honduras'));
		DB::table('country_codes')->insert(array('code'=>'HK','country'=>'Hong Kong'));
		DB::table('country_codes')->insert(array('code'=>'HR','country'=>'Hrvatska'));
		DB::table('country_codes')->insert(array('code'=>'HU','country'=>'Hungary'));
		DB::table('country_codes')->insert(array('code'=>'IS','country'=>'Iceland'));
		DB::table('country_codes')->insert(array('code'=>'IN','country'=>'India'));
		DB::table('country_codes')->insert(array('code'=>'ID','country'=>'Indonesia'));
		DB::table('country_codes')->insert(array('code'=>'IR','country'=>'Iran'));
		DB::table('country_codes')->insert(array('code'=>'IQ','country'=>'Iraq'));
		DB::table('country_codes')->insert(array('code'=>'IE','country'=>'Ireland'));
		DB::table('country_codes')->insert(array('code'=>'IL','country'=>'Israel'));
		DB::table('country_codes')->insert(array('code'=>'IT','country'=>'Italy'));
		DB::table('country_codes')->insert(array('code'=>'JM','country'=>'Jamaica'));
		DB::table('country_codes')->insert(array('code'=>'JP','country'=>'Japan'));
		DB::table('country_codes')->insert(array('code'=>'JO','country'=>'Jordan'));
		DB::table('country_codes')->insert(array('code'=>'KZ','country'=>'Kazakhstan'));
		DB::table('country_codes')->insert(array('code'=>'KE','country'=>'Kenya'));
		DB::table('country_codes')->insert(array('code'=>'KI','country'=>'Kiribati'));
		DB::table('country_codes')->insert(array('code'=>'KP','country'=>'Korea'));
		DB::table('country_codes')->insert(array('code'=>'KR','country'=>'Korea'));
		DB::table('country_codes')->insert(array('code'=>'KW','country'=>'Kuwait'));
		DB::table('country_codes')->insert(array('code'=>'KG','country'=>'Kyrgyz Republic'));
		DB::table('country_codes')->insert(array('code'=>'LA','country'=>'Lao People\'s Democratic Republic'));
		DB::table('country_codes')->insert(array('code'=>'LV','country'=>'Latvia'));
		DB::table('country_codes')->insert(array('code'=>'LB','country'=>'Lebanon'));
		DB::table('country_codes')->insert(array('code'=>'LS','country'=>'Lesotho'));
		DB::table('country_codes')->insert(array('code'=>'LR','country'=>'Liberia'));
		DB::table('country_codes')->insert(array('code'=>'LY','country'=>'Libyan Arab Jamahiriya'));
		DB::table('country_codes')->insert(array('code'=>'LI','country'=>'Liechtenstein'));
		DB::table('country_codes')->insert(array('code'=>'LT','country'=>'Lithuania'));
		DB::table('country_codes')->insert(array('code'=>'LU','country'=>'Luxembourg'));
		DB::table('country_codes')->insert(array('code'=>'MO','country'=>'Macao'));
		DB::table('country_codes')->insert(array('code'=>'MK','country'=>'Macedonia'));
		DB::table('country_codes')->insert(array('code'=>'MG','country'=>'Madagascar'));
		DB::table('country_codes')->insert(array('code'=>'MW','country'=>'Malawi'));
		DB::table('country_codes')->insert(array('code'=>'MY','country'=>'Malaysia'));
		DB::table('country_codes')->insert(array('code'=>'MV','country'=>'Maldives'));
		DB::table('country_codes')->insert(array('code'=>'ML','country'=>'Mali'));
		DB::table('country_codes')->insert(array('code'=>'MT','country'=>'Malta'));
		DB::table('country_codes')->insert(array('code'=>'MH','country'=>'Marshall Islands'));
		DB::table('country_codes')->insert(array('code'=>'MQ','country'=>'Martinique'));
		DB::table('country_codes')->insert(array('code'=>'MR','country'=>'Mauritania'));
		DB::table('country_codes')->insert(array('code'=>'MU','country'=>'Mauritius'));
		DB::table('country_codes')->insert(array('code'=>'YT','country'=>'Mayotte'));
		DB::table('country_codes')->insert(array('code'=>'MX','country'=>'Mexico'));
		DB::table('country_codes')->insert(array('code'=>'FM','country'=>'Micronesia'));
		DB::table('country_codes')->insert(array('code'=>'MD','country'=>'Moldova'));
		DB::table('country_codes')->insert(array('code'=>'MC','country'=>'Monaco'));
		DB::table('country_codes')->insert(array('code'=>'MN','country'=>'Mongolia'));
		DB::table('country_codes')->insert(array('code'=>'MS','country'=>'Montserrat'));
		DB::table('country_codes')->insert(array('code'=>'MA','country'=>'Morocco'));
		DB::table('country_codes')->insert(array('code'=>'MZ','country'=>'Mozambique'));
		DB::table('country_codes')->insert(array('code'=>'MM','country'=>'Myanmar'));
		DB::table('country_codes')->insert(array('code'=>'NA','country'=>'Namibia'));
		DB::table('country_codes')->insert(array('code'=>'NR','country'=>'Nauru'));
		DB::table('country_codes')->insert(array('code'=>'NP','country'=>'Nepal'));
		DB::table('country_codes')->insert(array('code'=>'AN','country'=>'Netherlands Antilles'));
		DB::table('country_codes')->insert(array('code'=>'NL','country'=>'Netherlands'));
		DB::table('country_codes')->insert(array('code'=>'NC','country'=>'New Caledonia'));
		DB::table('country_codes')->insert(array('code'=>'NZ','country'=>'New Zealand'));
		DB::table('country_codes')->insert(array('code'=>'NI','country'=>'Nicaragua'));
		DB::table('country_codes')->insert(array('code'=>'NE','country'=>'Niger'));
		DB::table('country_codes')->insert(array('code'=>'NG','country'=>'Nigeria'));
		DB::table('country_codes')->insert(array('code'=>'NU','country'=>'Niue'));
		DB::table('country_codes')->insert(array('code'=>'NF','country'=>'Norfolk Island'));
		DB::table('country_codes')->insert(array('code'=>'MP','country'=>'Northern Mariana Islands'));
		DB::table('country_codes')->insert(array('code'=>'NO','country'=>'Norway'));
		DB::table('country_codes')->insert(array('code'=>'OM','country'=>'Oman'));
		DB::table('country_codes')->insert(array('code'=>'PK','country'=>'Pakistan'));
		DB::table('country_codes')->insert(array('code'=>'PW','country'=>'Palau'));
		DB::table('country_codes')->insert(array('code'=>'PS','country'=>'Palestinian Territory'));
		DB::table('country_codes')->insert(array('code'=>'PA','country'=>'Panama'));
		DB::table('country_codes')->insert(array('code'=>'PG','country'=>'Papua New Guinea'));
		DB::table('country_codes')->insert(array('code'=>'PY','country'=>'Paraguay'));
		DB::table('country_codes')->insert(array('code'=>'PE','country'=>'Peru'));
		DB::table('country_codes')->insert(array('code'=>'PH','country'=>'Philippines'));
		DB::table('country_codes')->insert(array('code'=>'PN','country'=>'Pitcairn Island'));
		DB::table('country_codes')->insert(array('code'=>'PL','country'=>'Poland'));
		DB::table('country_codes')->insert(array('code'=>'PT','country'=>'Portugal'));
		DB::table('country_codes')->insert(array('code'=>'PR','country'=>'Puerto Rico'));
		DB::table('country_codes')->insert(array('code'=>'QA','country'=>'Qatar'));
		DB::table('country_codes')->insert(array('code'=>'RE','country'=>'Reunion'));
		DB::table('country_codes')->insert(array('code'=>'RO','country'=>'Romania'));
		DB::table('country_codes')->insert(array('code'=>'RU','country'=>'Russian Federation'));
		DB::table('country_codes')->insert(array('code'=>'RW','country'=>'Rwanda'));
		DB::table('country_codes')->insert(array('code'=>'SH','country'=>'St. Helena'));
		DB::table('country_codes')->insert(array('code'=>'KN','country'=>'St. Kitts and Nevis'));
		DB::table('country_codes')->insert(array('code'=>'LC','country'=>'St. Lucia'));
		DB::table('country_codes')->insert(array('code'=>'PM','country'=>'St. Pierre and Miquelon'));
		DB::table('country_codes')->insert(array('code'=>'VC','country'=>'St. Vincent and the Grenadines'));
		DB::table('country_codes')->insert(array('code'=>'WS','country'=>'Samoa'));
		DB::table('country_codes')->insert(array('code'=>'SM','country'=>'San Marino'));
		DB::table('country_codes')->insert(array('code'=>'ST','country'=>'Sao Tome and Principe'));
		DB::table('country_codes')->insert(array('code'=>'SA','country'=>'Saudi Arabia'));
		DB::table('country_codes')->insert(array('code'=>'SN','country'=>'Senegal'));
		DB::table('country_codes')->insert(array('code'=>'CS','country'=>'Serbia and Montenegro'));
		DB::table('country_codes')->insert(array('code'=>'SC','country'=>'Seychelles'));
		DB::table('country_codes')->insert(array('code'=>'SL','country'=>'Sierra Leone'));
		DB::table('country_codes')->insert(array('code'=>'SG','country'=>'Singapore'));
		DB::table('country_codes')->insert(array('code'=>'SK','country'=>'Slovakia'));
		DB::table('country_codes')->insert(array('code'=>'SI','country'=>'Slovenia'));
		DB::table('country_codes')->insert(array('code'=>'SB','country'=>'Solomon Islands'));
		DB::table('country_codes')->insert(array('code'=>'SO','country'=>'Somalia'));
		DB::table('country_codes')->insert(array('code'=>'ZA','country'=>'South Africa'));
		DB::table('country_codes')->insert(array('code'=>'GS','country'=>'South Georgia and the South Sandwich Islands'));
		DB::table('country_codes')->insert(array('code'=>'ES','country'=>'Spain'));
		DB::table('country_codes')->insert(array('code'=>'LK','country'=>'Sri Lanka'));
		DB::table('country_codes')->insert(array('code'=>'SD','country'=>'Sudan'));
		DB::table('country_codes')->insert(array('code'=>'SR','country'=>'Suriname'));
		DB::table('country_codes')->insert(array('code'=>'SJ','country'=>'Svalbard & Jan Mayen Islands'));
		DB::table('country_codes')->insert(array('code'=>'SZ','country'=>'Swaziland'));
		DB::table('country_codes')->insert(array('code'=>'SE','country'=>'Sweden'));
		DB::table('country_codes')->insert(array('code'=>'CH','country'=>'Switzerland'));
		DB::table('country_codes')->insert(array('code'=>'SY','country'=>'Syrian Arab Republic'));
		DB::table('country_codes')->insert(array('code'=>'TW','country'=>'Taiwan'));
		DB::table('country_codes')->insert(array('code'=>'TJ','country'=>'Tajikistan'));
		DB::table('country_codes')->insert(array('code'=>'TZ','country'=>'Tanzania'));
		DB::table('country_codes')->insert(array('code'=>'TH','country'=>'Thailand'));
		DB::table('country_codes')->insert(array('code'=>'TL','country'=>'Timor-Leste'));
		DB::table('country_codes')->insert(array('code'=>'TG','country'=>'Togo'));
		DB::table('country_codes')->insert(array('code'=>'TK','country'=>'Tokelau'));
		DB::table('country_codes')->insert(array('code'=>'TO','country'=>'Tonga'));
		DB::table('country_codes')->insert(array('code'=>'TT','country'=>'Trinidad and Tobago'));
		DB::table('country_codes')->insert(array('code'=>'TN','country'=>'Tunisia'));
		DB::table('country_codes')->insert(array('code'=>'TR','country'=>'Turkey'));
		DB::table('country_codes')->insert(array('code'=>'TM','country'=>'Turkmenistan'));
		DB::table('country_codes')->insert(array('code'=>'TC','country'=>'Turks and Caicos Islands'));
		DB::table('country_codes')->insert(array('code'=>'TV','country'=>'Tuvalu'));
		DB::table('country_codes')->insert(array('code'=>'VI','country'=>'US Virgin Islands'));
		DB::table('country_codes')->insert(array('code'=>'UG','country'=>'Uganda'));
		DB::table('country_codes')->insert(array('code'=>'UA','country'=>'Ukraine'));
		DB::table('country_codes')->insert(array('code'=>'AE','country'=>'United Arab Emirates'));
		DB::table('country_codes')->insert(array('code'=>'GB','country'=>'United Kingdom of Great Britain & N. Ireland'));
		DB::table('country_codes')->insert(array('code'=>'UM','country'=>'United States Minor Outlying Islands'));
		DB::table('country_codes')->insert(array('code'=>'US','country'=>'United States of America'));
		DB::table('country_codes')->insert(array('code'=>'UY','country'=>'Uruguay'));
		DB::table('country_codes')->insert(array('code'=>'UZ','country'=>'Uzbekistan'));
		DB::table('country_codes')->insert(array('code'=>'VU','country'=>'Vanuatu'));
		DB::table('country_codes')->insert(array('code'=>'VE','country'=>'Venezuela'));
		DB::table('country_codes')->insert(array('code'=>'VN','country'=>'Viet Nam'));
		DB::table('country_codes')->insert(array('code'=>'WF','country'=>'Wallis and Futuna Islands'));
		DB::table('country_codes')->insert(array('code'=>'EH','country'=>'Western Sahara'));
		DB::table('country_codes')->insert(array('code'=>'YE','country'=>'Yemen'));
		DB::table('country_codes')->insert(array('code'=>'ZM','country'=>'Zambia'));
		DB::table('country_codes')->insert(array('code'=>'ZW','country'=>'Zimbabwe'));
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('country_codes');
    }
}
